### ISSUE TITLE
Trouble building project

### ISSUE THREAD

**Issue by ak0ska** [BlueBrain/sbt-nexus#17]
Hello,

I encountered some problems trying to publish the project locally (in order to build nexus-iam):

``` sbt
sbt:sbt-nexus> publishLocal
[info] Updating {file:/home/ak0ska/git/sbt-nexus/}sbt-nexus...
[info] Wrote /home/ak0ska/git/sbt-nexus/target/scala-2.12/sbt-1.0/sbt-nexus-0.4.3-SNAPSHOT.pom
[warn]  module not found: com.typesafe.sbt#sbt-native-packager;1.2.2
[warn] ==== local: tried
[warn]   /home/ak0ska/.ivy2/local/com.typesafe.sbt/sbt-native-packager/scala_2.12/sbt_1.0/1.2.2/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/ak0ska/.sbt/preloaded/com.typesafe.sbt/sbt-native-packager/1.2.2/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/ak0ska/.sbt/preloaded/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.2.2/sbt-native-packager-1.2.2.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.2.2/sbt-native-packager-1.2.2.pom
[warn] ==== sbt-maven-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/maven-releases/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.2.2/sbt-native-packager-1.2.2.pom
[warn] ==== sbt-maven-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/typesafe/sbt/sbt-native-packager_2.12_1.0/1.2.2/sbt-native-packager-1.2.2.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.typesafe.sbt/sbt-native-packager/1.2.2/ivys/ivy.xml
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.typesafe.sbt/sbt-native-packager/1.2.2/ivys/ivy.xml
[warn]  module not found: com.lightbend.paradox#sbt-paradox;0.3.1
[warn] ==== local: tried
[warn]   /home/ak0ska/.ivy2/local/com.lightbend.paradox/sbt-paradox/scala_2.12/sbt_1.0/0.3.1/ivys/ivy.xml
[warn] ==== local-preloaded-ivy: tried
[warn]   /home/ak0ska/.sbt/preloaded/com.lightbend.paradox/sbt-paradox/0.3.1/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////home/ak0ska/.sbt/preloaded/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.3.1/sbt-paradox-0.3.1.pom
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.3.1/sbt-paradox-0.3.1.pom
[warn] ==== sbt-maven-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/maven-releases/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.3.1/sbt-paradox-0.3.1.pom
[warn] ==== sbt-maven-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/maven-snapshots/com/lightbend/paradox/sbt-paradox_2.12_1.0/0.3.1/sbt-paradox-0.3.1.pom
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.lightbend.paradox/sbt-paradox/0.3.1/ivys/ivy.xml
[warn] ==== sbt-ivy-snapshots: tried
[warn]   https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.lightbend.paradox/sbt-paradox/0.3.1/ivys/ivy.xml
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.typesafe.sbt#sbt-native-packager;1.2.2: not found
[warn]  :: com.lightbend.paradox#sbt-paradox;0.3.1: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.typesafe.sbt:sbt-native-packager:1.2.2 (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.lightbend.paradox:sbt-paradox:0.3.1 (scalaVersion=2.12, sbtVersion=1.0)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.typesafe.sbt:sbt-native-packager:1.2.2 (scalaVersion=2.12, sbtVersion=1.0) (/home/ak0ska/git/sbt-nexus/build.sbt#L59-60)
[warn]            +- ch.epfl.bluebrain.nexus:sbt-nexus:0.4.3-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[warn]          com.lightbend.paradox:sbt-paradox:0.3.1 (scalaVersion=2.12, sbtVersion=1.0) (/home/ak0ska/git/sbt-nexus/build.sbt#L60-61)
[warn]            +- ch.epfl.bluebrain.nexus:sbt-nexus:0.4.3-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.2.2: not found
[error] unresolved dependency: com.lightbend.paradox#sbt-paradox;0.3.1: not found
[error]         at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error]         at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:229)
[error]         at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:190)
[error]         at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error]         at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error]         at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error]         at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error]         at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error]         at xsbt.boot.Using$.withResource(Using.scala:10)
[error]         at xsbt.boot.Using$.apply(Using.scala:9)
[error]         at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error]         at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error]         at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error]         at xsbt.boot.Locks$.apply(Locks.scala:28)
[error]         at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:185)
[error]         at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:182)
[error]         at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:228)
[error]         at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:190)
[error]         at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error]         at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error]         at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:38)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:91)
[error]         at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:104)
[error]         at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:104)
[error]         at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:87)
[error]         at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error]         at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:118)
[error]         at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2353)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:64)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:266)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (*:update) sbt.librarymanagement.ResolveException: unresolved dependency: com.typesafe.sbt#sbt-native-packager;1.2.2: not found
[error] unresolved dependency: com.lightbend.paradox#sbt-paradox;0.3.1: not found
[error] Total time: 8 s, completed Nov 30, 2017 2:46:33 PM
```

The following changes solve the problem:
``` diff
diff --git a/build.sbt b/build.sbt
index f6731cb..b7b6aeb 100644
--- a/build.sbt
+++ b/build.sbt
@@ -56,5 +56,3 @@ addCommandAlias("rel",    ";release with-defaults")
 addSbtPlugin("org.scoverage"          %% "sbt-scoverage"       % "1.5.1")
 addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat"       % "1.0.7")
 addSbtPlugin("com.github.gseitz"       % "sbt-release"         % "1.0.6")
-addSbtPlugin("com.typesafe.sbt"        % "sbt-native-packager" % "1.2.2")
-addSbtPlugin("com.lightbend.paradox"   % "sbt-paradox"         % "0.3.1")
diff --git a/project/plugins.sbt b/project/plugins.sbt
index 6252086..ab93023 100644
--- a/project/plugins.sbt
+++ b/project/plugins.sbt
@@ -1,2 +1,3 @@
 addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.6")
-
+addSbtPlugin("com.typesafe.sbt"        % "sbt-native-packager" % "1.2.2")
+addSbtPlugin("com.lightbend.paradox"   % "sbt-paradox"         % "0.3.1")
```

May I ask why these plugins are added in the build.sbt instead of the plugins.sbt?

**Comment by bogdanromanx** [comment]
The change you describe is not correct in the sense that removing the lines from build.sbt and adding them to plugins will make those plugins apply only to the sbt-nexus build instead of the projects where the sbt-nexus plugin is being used.

Could you please test it again with the latest master, it should be just an sbt caching issue that may have been fixed in the latest releases?

**Comment by bogdanromanx** [comment]
The switch of artifact publishing to bintray resolves this issue. Closing.
